<a href="https://colab.research.google.com/github/merfab/IntegGit/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Initiate/Setup TensorFlow

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


Dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


Build Model 

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

Make Predictions

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.43472344, -0.70255184,  0.0095893 , -0.00260486, -0.31887183,
        -0.02885043, -0.95996594,  0.6147348 ,  0.8596004 , -0.11876722]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.13756448, 0.04411577, 0.08992343, 0.08883355, 0.06474765,
        0.08653239, 0.03410361, 0.16469646, 0.21039142, 0.07909124]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.4472365

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and Evaluate

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2933 - accuracy: 0.9159
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1406 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1063 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0864 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0741 - accuracy: 0.9764


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0705 - accuracy: 0.9776 - 495ms/epoch - 2ms/step


[0.07045513391494751, 0.9775999784469604]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.36096252e-08, 1.50738337e-08, 1.70159474e-05, 4.22099489e-04,
        3.71822260e-11, 2.67529174e-07, 5.56784165e-13, 9.99559343e-01,
        1.20457727e-07, 1.20230095e-06],
       [1.28180936e-05, 2.67227697e-05, 9.99945045e-01, 5.48845310e-06,
        6.36057316e-16, 6.96200868e-06, 2.39895911e-07, 3.92806820e-14,
        2.64050550e-06, 3.42840895e-11],
       [3.78257278e-06, 9.98537540e-01, 7.19980599e-05, 7.65603036e-05,
        1.86784921e-04, 5.90236559e-05, 1.14000395e-05, 6.94475777e-04,
        3.26505135e-04, 3.19488536e-05],
       [9.99830842e-01, 7.19129367e-10, 1.56622016e-04, 5.92854235e-07,
        2.97795957e-08, 4.05718083e-06, 5.09474012e-06, 4.49682716e-07,
        1.34152423e-08, 2.25644544e-06],
       [1.22434949e-05, 1.17890406e-10, 1.18939834e-05, 5.59548994e-07,
        9.86855447e-01, 5.05853954e-08, 6.22821335e-06, 7.83720025e-05,
        6.95050289e-07, 1.30345626e-02]], dtype=float32)>